(load "./part2.lisp")
(defun checker (a)
	(if (or (eq a NIL) (eq (car a) NIL))
		(return-from checker a)
		(if (listp a)
			(if (listp (car a))
				(checker (merger (car a) (cdr a)))
				(cons (car a) (checker (cdr a)))
			) 
		)
	)
)