(load "./part2.lisp")
(defun checker (a)
	(if (not (eq a NIL))
		(if (listp a)
			(if (not (eq (car a) NIL))
				(if (listp (car a)) 
					(checker (merger (car a) (cdr a)))
					(cons (car a) (checker (cdr a)))
				)
			)
		)
	)
)