(load "part2.lisp")
(defun inserti (inputList target object) 
	(if (eq target 0) 
		(merger object inputList)
		(if (atom inputList) 
			(list object)
			(merger (car inputList) (inserti (cdr inputList) (- target 1) object))
		)
	)
)